### ISSUE TITLE
kafka需要什么版本的

### ISSUE THREAD

**Issue by liaozhuoran** [gitbitex/gitbitex-spot#13]
kafka需要什么版本的，我装了最新版，一直报错：
 ERROR Closing socket for /0:0:0:0:0:0:0:1 because of error (kafka.network.Processor)
kafka.common.KafkaException: Wrong request type 18
	at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:64)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
	at kafka.network.Processor.read(SocketServer.scala:450)
	at kafka.network.Processor.run(SocketServer.scala:340)
	at java.lang.Thread.run(Thread.java:745)

**Comment by greensheng** [comment]
kafka_2.12-2.3.0 测试通过
