### ISSUE TITLE
Order book stream panic

### ISSUE THREAD

**Issue by amitsharma8891** [gitbitex/gitbitex-spot#19]
Getting the following error when trying to place the order.

panic: should not happen : &{Base:{Type:match Sequence:5 ProductId:ITD-USDT Time:2019-12-09 05:59:55.480850451 +0000 UTC} TradeId:1 TakerOrderId:5820841 MakerOrderId:5820837 Side:sell Price:1.1 Size:10}

goroutine 195 [running]:
github.com/gitbitex/gitbitex-spot/pushing.(*OrderBookStream).runApplier(0xc00008cc40)
        /home/ubuntu/go/src/gitbitex-spot/pushing/order_book_stream.go:114 +0x832
created by github.com/gitbitex/gitbitex-spot/pushing.(*OrderBookStream).Start
        /home/ubuntu/go/src/gitbitex-spot/pushing/order_book_stream.go:69 +0x8d
exit status 2

**Comment by ablewolf** [comment]
这个问题得以解决了吗？我也遇到相同问题，在这个地方如果OrderBook 数据没有推到redis ,或者redis 数据为空，都有可能引发这个问题，但是其根本原因并不是很明白
