### ISSUE TITLE
web front npm won't start

### ISSUE THREAD

**Issue by nerotiger** [gitbitex/gitbitex-spot#26]
> gitbitex@1.0.0 build
> gulp --env=prod

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (./extest/gitbitex-web/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (./extest/gitbitex-web/node_modules/undertaker/lib/task.js:13:8)
    at ./extest/gitbitex-web/gulpfile.js:59:25
    at createTask (./extest/gitbitex-web/gulpfile.js:62:11)
    at Object.<anonymous> (./extest/gitbitex-web/gulpfile.js:178:5)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Comment by xfiveit** [comment]
This is my problem too
